apiVersion: v1
kind: Service
metadata:
  name: apptitou2 #nom du service unique (trio)
spec:
  selector:
    app: apptitou2 # c'est bien le label mis au pod qui est recherché local à un namespace
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # port standard


      